In [1]:
# import library

import pandas as pd

In [2]:
# get dataframe

df = pd.read_excel(r'D:\MyWorks\DataForProject\Data For RegEx\Data for Project1.xlsx',sheet_name='data')

df

,No,President,Born,Age atstart of precidency,Age atend of presidency,Post-presidencytimespan,Died,Age
0,1,George Washington,"Feb 22,\n1732[a]","87 years, 58 daysSep 11, 1989","25 years, 183 daysApr 24, 1929","21 years, 122 days","May 21,\n1948","39 years, 207 days"
1,2,John Adam,"Apr 13, 1914","78 years, 31 daysJan 22, 1951","80 years, 3 daysOct 2, 1932","44 years, 268 days","Jan 15, 1944","97 years, 78 days"
2,3,Thomas Jefferson,"May 25, 1997[a]","24 years, 289 daysOct 28, 1989","66 years, 272 daysMay 27, 1982","30 years, 294 days","Mar 30, 1918","89 years, 304 days"
3,4,James Madison,"Sep 26, 1991","75 years, 97 daysJan 19, 1968","42 years, 211 daysAug 20, 1989","48 years, 89 days","Jul 15, \n1918","64 years,\n235 days"
4,5,James Monroe,"Mar 25, 1972","50 years, 361 daysJan 18, 1992","12 years, 101 daysDec 30, 1996","25 years, 299 days","Aug 30, 1958","74 years, 355 days"
5,6,John Quincy Adams,"Jul 12, 1994","13 years, 121 daysFeb 25, 1969","7 years, 55 daysOct 16, 1952","67 years, 163 days","Jan 20, 1976","43 years, 276 days"
6,7,Andrew Jackson,"Oct 4, 1982","47 years, 76 daysMay 30, 1953","33 years, 50 daysMar 26, 1989","76 years, 327 days","Aug 26, 1950","2 years, 27 days"
7,8,Martin Van Buren,"May 15, 1910","92 years, 42 daysNov 10, 1948","60 years, 53 daysFeb 11, 1983","9 years, 301 days","May 6, 1980","63 years, 40 days"
8,9,William H. Harrison,"Aug 18, 1971[a]","99 years, 341 daysMay 6, 1989","9 years, 252 daysMar 26, 1973","45 years, 138 days","Jan 24, 1959","31 years, 235 days"
9,10,John Tyler,"Dec 8, 1936","38 years, 336 daysJan 18, 1916","46 years, 148 daysSep 6, 1997","15 years, 28 days","Sep 17, \n1950","6 years, 342 days"
10,11,James K. Polk,"Apr 15, 1925","46 years, 209 daysApr 22, 1924","76 years, 343 daysJan 1, 1946","63 years, 127 days","Aug 22, \n1955","18 years, 123 days"
11,12,James Bond,"Apr 16, 1926[a]","33 years, 7 daysDec 21, 1916","40 years, 155 daysJan 14, 1928","13 years, 298 days","May 13, 1912","57 years, 307 days"
12,13,Brand Pit,"Sep 5, 1992","15 years, 115 daysMay 6, 1989","22 years, 290 daysFeb 18, 1916","53 years, 97 days","Apr 2, 1943","83 years, 281 days"
13,14,Jimmy K. Wu,"Feb 13, 1981","80 years, 186 daysMar 24, 1962","46 years, 87 daysOct 28, 1998","55 years, 10 days","Apr 28, 1955","30 years, 240 days"
14,15,Kim Jong Ill,"Oct 6, 1952[a]","35 years, 121 daysOct 25, 1951","51 years, 319 daysApr 8, 1940","38 years, 350 days","Oct 3, \n1957","93 years, 226 days"
15,16,Mike Tison,"Nov 26, 1937[a]","36 years, 359 daysNov 24, 1952","78 years, 28 daysJan 13, 1957","2 years, 134 days","Feb 16, 1991","99 years, 283 days"
16,17,Talor Swift,"Oct 16, 1911","75 years, 55 daysOct 25, 1923","76 years, 286 daysApr 16, 1980","8 years, 278 days","May 21, 1969","97 years, 186 days"
17,18,Satoshi Eka,"Jan 22, 1989","99 years, 122 daysMay 6, 1981","23 years, 360 daysJan 30, 1975","64 years, 123 days","Dec 27, \n1934","24 years, 279 days"
18,19,Jame C. Johnson,"Sep 18, 1948","74 years, 350 daysJul 23, 1971","52 years, 67 daysMar 29, 1959","5 years, 175 days","Jan 25, \n1936","57 years, 317 days"
19,20,BB King,"Feb 11, 1933","84 years, 116 daysMay 30, 1912","14 years, 326 daysNov 7, 1925","27 years, 356 days","Feb 18, \n1936","49 years, 62 days"

In [3]:
# extract first name, middle name, and last name from 'President' column by using regular expression

df['First Name'] = df['President'].str.extract('(\w+)')
df['Middle Name'] = df['President'].str.extract('(?:[\w]+\s)(\w+[.]?)(?:\s\w+)')
df['Last Name'] = df['President'].str.extract('([\w+]+$)')

df

,No,President,Born,Age atstart of precidency,Age atend of presidency,Post-presidencytimespan,Died,Age,First Name,Middle Name,Last Name
0,1,George Washington,"Feb 22,\n1732[a]","87 years, 58 daysSep 11, 1989","25 years, 183 daysApr 24, 1929","21 years, 122 days","May 21,\n1948","39 years, 207 days",George,NaN,Washington
1,2,John Adam,"Apr 13, 1914","78 years, 31 daysJan 22, 1951","80 years, 3 daysOct 2, 1932","44 years, 268 days","Jan 15, 1944","97 years, 78 days",John,NaN,Adam
2,3,Thomas Jefferson,"May 25, 1997[a]","24 years, 289 daysOct 28, 1989","66 years, 272 daysMay 27, 1982","30 years, 294 days","Mar 30, 1918","89 years, 304 days",Thomas,NaN,Jefferson
3,4,James Madison,"Sep 26, 1991","75 years, 97 daysJan 19, 1968","42 years, 211 daysAug 20, 1989","48 years, 89 days","Jul 15, \n1918","64 years,\n235 days",James,NaN,Madison
4,5,James Monroe,"Mar 25, 1972","50 years, 361 daysJan 18, 1992","12 years, 101 daysDec 30, 1996","25 years, 299 days","Aug 30, 1958","74 years, 355 days",James,NaN,Monroe
5,6,John Quincy Adams,"Jul 12, 1994","13 years, 121 daysFeb 25, 1969","7 years, 55 daysOct 16, 1952","67 years, 163 days","Jan 20, 1976","43 years, 276 days",John,Quincy,Adams
6,7,Andrew Jackson,"Oct 4, 1982","47 years, 76 daysMay 30, 1953","33 years, 50 daysMar 26, 1989","76 years, 327 days","Aug 26, 1950","2 years, 27 days",Andrew,NaN,Jackson
7,8,Martin Van Buren,"May 15, 1910","92 years, 42 daysNov 10, 1948","60 years, 53 daysFeb 11, 1983","9 years, 301 days","May 6, 1980","63 years, 40 days",Martin,Van,Buren
8,9,William H. Harrison,"Aug 18, 1971[a]","99 years, 341 daysMay 6, 1989","9 years, 252 daysMar 26, 1973","45 years, 138 days","Jan 24, 1959","31 years, 235 days",William,H.,Harrison
9,10,John Tyler,"Dec 8, 1936","38 years, 336 daysJan 18, 1916","46 years, 148 daysSep 6, 1997","15 years, 28 days","Sep 17, \n1950","6 years, 342 days",John,NaN,Tyler
10,11,James K. Polk,"Apr 15, 1925","46 years, 209 daysApr 22, 1924","76 years, 343 daysJan 1, 1946","63 years, 127 days","Aug 22, \n1955","18 years, 123 days",James,K.,Polk
11,12,James Bond,"Apr 16, 1926[a]","33 years, 7 daysDec 21, 1916","40 years, 155 daysJan 14, 1928","13 years, 298 days","May 13, 1912","57 years, 307 days",James,NaN,Bond
12,13,Brand Pit,"Sep 5, 1992","15 years, 115 daysMay 6, 1989","22 years, 290 daysFeb 18, 1916","53 years, 97 days","Apr 2, 1943","83 years, 281 days",Brand,NaN,Pit
13,14,Jimmy K. Wu,"Feb 13, 1981","80 years, 186 daysMar 24, 1962","46 years, 87 daysOct 28, 1998","55 years, 10 days","Apr 28, 1955","30 years, 240 days",Jimmy,K.,Wu
14,15,Kim Jong Ill,"Oct 6, 1952[a]","35 years, 121 daysOct 25, 1951","51 years, 319 daysApr 8, 1940","38 years, 350 days","Oct 3, \n1957","93 years, 226 days",Kim,Jong,Ill
15,16,Mike Tison,"Nov 26, 1937[a]","36 years, 359 daysNov 24, 1952","78 years, 28 daysJan 13, 1957","2 years, 134 days","Feb 16, 1991","99 years, 283 days",Mike,NaN,Tison
16,17,Talor Swift,"Oct 16, 1911","75 years, 55 daysOct 25, 1923","76 years, 286 daysApr 16, 1980","8 years, 278 days","May 21, 1969","97 years, 186 days",Talor,NaN,Swift
17,18,Satoshi Eka,"Jan 22, 1989","99 years, 122 daysMay 6, 1981","23 years, 360 daysJan 30, 1975","64 years, 123 days","Dec 27, \n1934","24 years, 279 days",Satoshi,NaN,Eka
18,19,Jame C. Johnson,"Sep 18, 1948","74 years, 350 daysJul 23, 1971","52 years, 67 daysMar 29, 1959","5 years, 175 days","Jan 25, \n1936","57 years, 317 days",Jame,C.,Johnson
19,20,BB King,"Feb 11, 1933","84 years, 116 daysMay 30, 1912","14 years, 326 daysNov 7, 1925","27 years, 356 days","Feb 18, \n1936","49 years, 62 days",BB,NaN,King

In [4]:
# use regular expression to clean birthdate data in 'Born' column

df['Born'] = df['Born'].str.extract('(\w{1,3}\s\d{1,2}[,]\s\d{1,4})')

df

,No,President,Born,Age atstart of precidency,Age atend of presidency,Post-presidencytimespan,Died,Age,First Name,Middle Name,Last Name
0,1,George Washington,"Feb 22,\n1732","87 years, 58 daysSep 11, 1989","25 years, 183 daysApr 24, 1929","21 years, 122 days","May 21,\n1948","39 years, 207 days",George,NaN,Washington
1,2,John Adam,"Apr 13, 1914","78 years, 31 daysJan 22, 1951","80 years, 3 daysOct 2, 1932","44 years, 268 days","Jan 15, 1944","97 years, 78 days",John,NaN,Adam
2,3,Thomas Jefferson,"May 25, 1997","24 years, 289 daysOct 28, 1989","66 years, 272 daysMay 27, 1982","30 years, 294 days","Mar 30, 1918","89 years, 304 days",Thomas,NaN,Jefferson
3,4,James Madison,"Sep 26, 1991","75 years, 97 daysJan 19, 1968","42 years, 211 daysAug 20, 1989","48 years, 89 days","Jul 15, \n1918","64 years,\n235 days",James,NaN,Madison
4,5,James Monroe,"Mar 25, 1972","50 years, 361 daysJan 18, 1992","12 years, 101 daysDec 30, 1996","25 years, 299 days","Aug 30, 1958","74 years, 355 days",James,NaN,Monroe
5,6,John Quincy Adams,"Jul 12, 1994","13 years, 121 daysFeb 25, 1969","7 years, 55 daysOct 16, 1952","67 years, 163 days","Jan 20, 1976","43 years, 276 days",John,Quincy,Adams
6,7,Andrew Jackson,"Oct 4, 1982","47 years, 76 daysMay 30, 1953","33 years, 50 daysMar 26, 1989","76 years, 327 days","Aug 26, 1950","2 years, 27 days",Andrew,NaN,Jackson
7,8,Martin Van Buren,"May 15, 1910","92 years, 42 daysNov 10, 1948","60 years, 53 daysFeb 11, 1983","9 years, 301 days","May 6, 1980","63 years, 40 days",Martin,Van,Buren
8,9,William H. Harrison,"Aug 18, 1971","99 years, 341 daysMay 6, 1989","9 years, 252 daysMar 26, 1973","45 years, 138 days","Jan 24, 1959","31 years, 235 days",William,H.,Harrison
9,10,John Tyler,"Dec 8, 1936","38 years, 336 daysJan 18, 1916","46 years, 148 daysSep 6, 1997","15 years, 28 days","Sep 17, \n1950","6 years, 342 days",John,NaN,Tyler
10,11,James K. Polk,"Apr 15, 1925","46 years, 209 daysApr 22, 1924","76 years, 343 daysJan 1, 1946","63 years, 127 days","Aug 22, \n1955","18 years, 123 days",James,K.,Polk
11,12,James Bond,"Apr 16, 1926","33 years, 7 daysDec 21, 1916","40 years, 155 daysJan 14, 1928","13 years, 298 days","May 13, 1912","57 years, 307 days",James,NaN,Bond
12,13,Brand Pit,"Sep 5, 1992","15 years, 115 daysMay 6, 1989","22 years, 290 daysFeb 18, 1916","53 years, 97 days","Apr 2, 1943","83 years, 281 days",Brand,NaN,Pit
13,14,Jimmy K. Wu,"Feb 13, 1981","80 years, 186 daysMar 24, 1962","46 years, 87 daysOct 28, 1998","55 years, 10 days","Apr 28, 1955","30 years, 240 days",Jimmy,K.,Wu
14,15,Kim Jong Ill,"Oct 6, 1952","35 years, 121 daysOct 25, 1951","51 years, 319 daysApr 8, 1940","38 years, 350 days","Oct 3, \n1957","93 years, 226 days",Kim,Jong,Ill
15,16,Mike Tison,"Nov 26, 1937","36 years, 359 daysNov 24, 1952","78 years, 28 daysJan 13, 1957","2 years, 134 days","Feb 16, 1991","99 years, 283 days",Mike,NaN,Tison
16,17,Talor Swift,"Oct 16, 1911","75 years, 55 daysOct 25, 1923","76 years, 286 daysApr 16, 1980","8 years, 278 days","May 21, 1969","97 years, 186 days",Talor,NaN,Swift
17,18,Satoshi Eka,"Jan 22, 1989","99 years, 122 daysMay 6, 1981","23 years, 360 daysJan 30, 1975","64 years, 123 days","Dec 27, \n1934","24 years, 279 days",Satoshi,NaN,Eka
18,19,Jame C. Johnson,"Sep 18, 1948","74 years, 350 daysJul 23, 1971","52 years, 67 daysMar 29, 1959","5 years, 175 days","Jan 25, \n1936","57 years, 317 days",Jame,C.,Johnson
19,20,BB King,"Feb 11, 1933","84 years, 116 daysMay 30, 1912","14 years, 326 daysNov 7, 1925","27 years, 356 days","Feb 18, \n1936","49 years, 62 days",BB,NaN,King

In [5]:
# extract Year, Days and Dates from 'Age atstart of precidency' column

df['Years of Presidency'] = df['Age atstart of precidency'].str.extract('(\d{1,2})(?:\s)(?:\w+)(?:,)(?:\s)(?:\d{1,3})(?:\s)(?:\w{4})(?:\w.*)')
df['Days of Presidency'] = df['Age atstart of precidency'].str.extract('(?:\d{1,2})(?:\s)(?:\w+)(?:,)(?:\s)(\d{1,3})(?:\s)(?:\w{4})(?:\w.*)')
df['Date of Presidency'] = df['Age atstart of precidency'].str.extract('(?:\d{1,2})(?:\s)(?:\w+)(?:,)(?:\s)(?:\d{1,3})(?:\s)(?:\w{4})(\w.*)')

df

,No,President,Born,Age atstart of precidency,Age atend of presidency,Post-presidencytimespan,Died,Age,First Name,Middle Name,Last Name,Years of Presidency,Days of Presidency,Date of Presidency
0,1,George Washington,"Feb 22,\n1732","87 years, 58 daysSep 11, 1989","25 years, 183 daysApr 24, 1929","21 years, 122 days","May 21,\n1948","39 years, 207 days",George,NaN,Washington,87,58,"Sep 11, 1989"
1,2,John Adam,"Apr 13, 1914","78 years, 31 daysJan 22, 1951","80 years, 3 daysOct 2, 1932","44 years, 268 days","Jan 15, 1944","97 years, 78 days",John,NaN,Adam,78,31,"Jan 22, 1951"
2,3,Thomas Jefferson,"May 25, 1997","24 years, 289 daysOct 28, 1989","66 years, 272 daysMay 27, 1982","30 years, 294 days","Mar 30, 1918","89 years, 304 days",Thomas,NaN,Jefferson,24,289,"Oct 28, 1989"
3,4,James Madison,"Sep 26, 1991","75 years, 97 daysJan 19, 1968","42 years, 211 daysAug 20, 1989","48 years, 89 days","Jul 15, \n1918","64 years,\n235 days",James,NaN,Madison,75,97,"Jan 19, 1968"
4,5,James Monroe,"Mar 25, 1972","50 years, 361 daysJan 18, 1992","12 years, 101 daysDec 30, 1996","25 years, 299 days","Aug 30, 1958","74 years, 355 days",James,NaN,Monroe,50,361,"Jan 18, 1992"
5,6,John Quincy Adams,"Jul 12, 1994","13 years, 121 daysFeb 25, 1969","7 years, 55 daysOct 16, 1952","67 years, 163 days","Jan 20, 1976","43 years, 276 days",John,Quincy,Adams,13,121,"Feb 25, 1969"
6,7,Andrew Jackson,"Oct 4, 1982","47 years, 76 daysMay 30, 1953","33 years, 50 daysMar 26, 1989","76 years, 327 days","Aug 26, 1950","2 years, 27 days",Andrew,NaN,Jackson,47,76,"May 30, 1953"
7,8,Martin Van Buren,"May 15, 1910","92 years, 42 daysNov 10, 1948","60 years, 53 daysFeb 11, 1983","9 years, 301 days","May 6, 1980","63 years, 40 days",Martin,Van,Buren,92,42,"Nov 10, 1948"
8,9,William H. Harrison,"Aug 18, 1971","99 years, 341 daysMay 6, 1989","9 years, 252 daysMar 26, 1973","45 years, 138 days","Jan 24, 1959","31 years, 235 days",William,H.,Harrison,99,341,"May 6, 1989"
9,10,John Tyler,"Dec 8, 1936","38 years, 336 daysJan 18, 1916","46 years, 148 daysSep 6, 1997","15 years, 28 days","Sep 17, \n1950","6 years, 342 days",John,NaN,Tyler,38,336,"Jan 18, 1916"
10,11,James K. Polk,"Apr 15, 1925","46 years, 209 daysApr 22, 1924","76 years, 343 daysJan 1, 1946","63 years, 127 days","Aug 22, \n1955","18 years, 123 days",James,K.,Polk,46,209,"Apr 22, 1924"
11,12,James Bond,"Apr 16, 1926","33 years, 7 daysDec 21, 1916","40 years, 155 daysJan 14, 1928","13 years, 298 days","May 13, 1912","57 years, 307 days",James,NaN,Bond,33,7,"Dec 21, 1916"
12,13,Brand Pit,"Sep 5, 1992","15 years, 115 daysMay 6, 1989","22 years, 290 daysFeb 18, 1916","53 years, 97 days","Apr 2, 1943","83 years, 281 days",Brand,NaN,Pit,15,115,"May 6, 1989"
13,14,Jimmy K. Wu,"Feb 13, 1981","80 years, 186 daysMar 24, 1962","46 years, 87 daysOct 28, 1998","55 years, 10 days","Apr 28, 1955","30 years, 240 days",Jimmy,K.,Wu,80,186,"Mar 24, 1962"
14,15,Kim Jong Ill,"Oct 6, 1952","35 years, 121 daysOct 25, 1951","51 years, 319 daysApr 8, 1940","38 years, 350 days","Oct 3, \n1957","93 years, 226 days",Kim,Jong,Ill,35,121,"Oct 25, 1951"
15,16,Mike Tison,"Nov 26, 1937","36 years, 359 daysNov 24, 1952","78 years, 28 daysJan 13, 1957","2 years, 134 days","Feb 16, 1991","99 years, 283 days",Mike,NaN,Tison,36,359,"Nov 24, 1952"
16,17,Talor Swift,"Oct 16, 1911","75 years, 55 daysOct 25, 1923","76 years, 286 daysApr 16, 1980","8 years, 278 days","May 21, 1969","97 years, 186 days",Talor,NaN,Swift,75,55,"Oct 25, 1923"
17,18,Satoshi Eka,"Jan 22, 1989","99 years, 122 daysMay 6, 1981","23 years, 360 daysJan 30, 1975","64 years, 123 days","Dec 27, \n1934","24 years, 279 days",Satoshi,NaN,Eka,99,122,"May 6, 1981"
18,19,Jame C. Johnson,"Sep 18, 1948","74 years, 350 daysJul 23, 1971","52 years, 67 daysMar 29, 1959","5 years, 175 days","Jan 25, \n1936","57 years, 317 days",Jame,C.,Johnson,74,350,"Jul 23, 1971"
19,20,BB King,"Feb 11, 1933","84 years, 116 daysMay 30, 1912","14 years, 326 daysNov 7, 1925","27 years, 356 days","Feb 18, \n1936","49 years, 62 days",BB,NaN,King,84,116,"May 30, 1912"